package site.duqian.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import site.duqian.greendao.demo1.Note;
import site.duqian.greendao.Music;

import site.duqian.greendao.NoteDao;
import site.duqian.greendao.MusicDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig musicDaoConfig;

    private final NoteDao noteDao;
    private final MusicDao musicDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        musicDaoConfig = daoConfigMap.get(MusicDao.class).clone();
        musicDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        musicDao = new MusicDao(musicDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(Music.class, musicDao);
    }
    
    public void clear() {
        noteDaoConfig.clearIdentityScope();
        musicDaoConfig.clearIdentityScope();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public MusicDao getMusicDao() {
        return musicDao;
    }

}
