# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Android专栏-杜乾，Dusan's blog
subtitle: Android Developer
description: Words about dusan's ideas,notes,android development,blog,projects,and so on.
author: Dusan-杜乾
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://duqian.site/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map: #[Android, Java, Web, Native]

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

index_generator:
  per_page: 10 ##首頁默認10篇文章標題 如果值爲0不分頁

archive_generator:
  per_page: 10 ##歸檔頁面默認10篇文章標題
  yearly: true  ##生成年視圖
  monthly: true ##生成月視圖
tag_generator:
  per_page: 10 ##標籤分類頁面默認10篇文章

category_generator:
   per_page: 10 ###分類頁面默認10篇文章

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yilia # landscape huno

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/duqian291902259/duqian291902259.github.io.git
  branch: master
